version: '3.8'

services:
  claude-proxy:
    build: .
    ports:
      - "8085:8085"
    environment:
      # Required: Set your target provider API key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      
      # Model configuration
      - CLAUDE_PROXY_BIG_MODEL=${CLAUDE_PROXY_BIG_MODEL:-gpt-4o}
      - CLAUDE_PROXY_SMALL_MODEL=${CLAUDE_PROXY_SMALL_MODEL:-gpt-4o-mini}
      
      # Server settings
      - CLAUDE_PROXY_HOST=0.0.0.0
      - CLAUDE_PROXY_PORT=8085
      - CLAUDE_PROXY_LOG_LEVEL=${CLAUDE_PROXY_LOG_LEVEL:-INFO}
      
      # Request settings
      - CLAUDE_PROXY_REQUEST_TIMEOUT=${CLAUDE_PROXY_REQUEST_TIMEOUT:-90}
      - CLAUDE_PROXY_MAX_TOKENS_LIMIT=${CLAUDE_PROXY_MAX_TOKENS_LIMIT:-4096}
      
      # Optional: Proxy authentication
      - CLAUDE_PROXY_AUTH_KEY=${CLAUDE_PROXY_AUTH_KEY}
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Restart policy for production
    restart: unless-stopped
    
    # Resource limits (optional, adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M