version: '3.8'

services:
  claude-proxy:
    build: .
    ports:
      - "8085:8085"
    environment:
      # Required: Set your OpenAI-compatible API key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      
      # Model configuration
      - BIG_MODEL=${BIG_MODEL:-gpt-4o}
      - SMALL_MODEL=${SMALL_MODEL:-gpt-4o-mini}
      
      # Server settings
      - HOST=0.0.0.0
      - PORT=8085
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Request settings
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-90}
      - MAX_TOKENS_LIMIT=${MAX_TOKENS_LIMIT:-4096}
      
      # Optional: API key validation
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Restart policy for production
    restart: unless-stopped
    
    # Resource limits (optional, adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M